cursor #d8e5e8
cursor_text_color #bcc9cc

foreground            #d8e5e8
background            #091518
selection_foreground  #0a3445
selection_background  #a7cce0
url_color             #00daf6

color0   #091518
color1   #ff0158
color2   #00f616
color3   #ffed00
color4   #00cfe9
color5   #006471
color6   #00daf6
color7   #e0fbff
color8   #879d9f
color9   #ff3f81
color10  #4cff5d
color11  #fff24c
color12  #26e6ff
color13  #4ceaff
color14  #8cf1ff
color15  #f2fdff
