cursor #e2e1ef
cursor_text_color #c5c5d3

foreground            #e2e1ef
background            #11131c
selection_foreground  #302c4c
selection_background  #c8c2ea
url_color             #b8c3ff

color0   #11131c
color1   #ff7297
color2   #7fff94
color3   #ffd772
color4   #a1adf2
color5   #394376
color6   #b8c3ff
color7   #eff2ff
color8   #999ba5
color9   #ff9fb8
color10  #a5ffb4
color11  #ffe6a5
color12  #c2cbff
color13  #cdd5ff
color14  #dfe4ff
color15  #f8f9ff
